[FIX 7078] better error messages
polyswarm/ppdns-chrome-extension pull request #48
Opened 2024-10-02 22:11 UTC by alanjds

Better handling of errors, and more informative error messages. Most of them include the last day that an ingestion worked, and they all mention that failed data will be stored to be retried later.

2024-10-02 22:12 UTC, alanjds commented on src/pages/Background/index.js
> +    + '\n\xa0\nClick here to open polyswarm.network/account/api-keys in a new tab');
Native english speakers, please double check this piece.

2024-10-02 22:13 UTC, alanjds commented on src/pages/Background/index.js
> +                + '\nLast successful transmission was ' + lastSuccess),
Native english speakers, please double check this piece. Including the title.

Please send suggestions via Github if possible.

2024-10-02 22:13 UTC, alanjds commented on src/pages/Background/index.js
> +                + '\nLast successful transmission was ' + lastSuccess),
Native english speakers, please double check this piece.

2024-10-02 22:13 UTC, alanjds commented on src/pages/Background/index.js
> +      message = 'Last successful submission was ' + lastSuccess + '.\nWill keep the data and try again soon.';
Native english speakers, please double check this piece.

2024-10-02 22:15 UTC, alanjds commented on src/pages/Background/index.js
> +      return 'by ' + lastDate.toLocaleDateString()
Native english speakers, please double check this piece.

The idea is to return `today` or `by 2024/12/20` or what makes sense in the browser language settings.

That will turn into `last time it worked was by 2024...` or `last time it worked was today.`
If this is not correct in English, please provide a suggestion for the `by ` thing.

2024-10-02 22:18 UTC, alanjds commented on src/pages/Background/index.js
> +      return 'by ' + lastDate.toLocaleDateString()
@supernothing & @mrtizmoatwork I am marking you here to be able to check the English spellings.

2024-10-02 23:47 UTC, mjbradford89 requested changes
Updated with some English suggestions.

Also unrelated to your changes, I noticed the API key validation is still using v2 here: https://github.com/polyswarm/ppdns-chrome-extension/pull/48/files#diff-b6bb0030ac3f7012a3807915b291ab879b577c13cbbb3203f0b35edeb1b54481R95

Would you be able to change that to v3 in this PR please?  I think the v2 api is no longer working.

2024-10-02 23:47 UTC, mjbradford89 commented on src/pages/Background/index.js
> +    + '\n\xa0\nClick here to open polyswarm.network/account/api-keys in a new tab');
```suggestion
    let message = ('Your telemetry data will be saved locally until you enter an API Key from your account settings.'
    + '\n\xa0\nClick here to open polyswarm.network/account/api-keys in a new tab');
```

2024-10-02 23:47 UTC, mjbradford89 commented on src/pages/Background/index.js
> +                + '\nLast successful transmission was ' + lastSuccess),
```suggestion
      title: 'We had an issue submitting telemetry data.',
      message: ('The data will be saved and resubmitted as soon as it is possible.'
                + '\nLast successful transmission was ' + lastSuccess),
```

2024-10-02 23:47 UTC, mjbradford89 commented on src/pages/Background/index.js
> +                + '\nLast successful transmission was ' + lastSuccess),
```suggestion
      title: 'There was an issue connecting to the internet.',
      message: ('The data will be saved and resubmitted once the connection is fixed .'
                + '\nLast successful transmission was ' + lastSuccess),
```

2024-10-02 23:47 UTC, mjbradford89 commented on src/pages/Background/index.js
> +      message = 'Last successful submission was ' + lastSuccess + '.\nWill keep the data and try again soon.';
```suggestion
    if (lastSuccess == 'today'){
      message = 'The data could not be sent right now, but some data has been sent today already.\nIt will be saved and resubmitted again soon.';
    }else{
      message = 'There is an issue submitting telemetry data. Last successful submission was ' + lastSuccess + '.\nOnce the issue is fixed the data will be resubmitted.';
```

2024-10-02 23:47 UTC, mjbradford89 commented on src/pages/Background/index.js
> +      return 'by ' + lastDate.toLocaleDateString()
```suggestion
      return 'on ' + lastDate.toLocaleDateString()
```

I think this sounds right:
>last time it worked was on 2024/12/20

2024-10-04 10:29 UTC, alanjds commented on src/pages/Background/index.js
> +                + '\nLast successful transmission was ' + lastSuccess),
I updated the message but the title became too big for one line:
![Screenshot_20241004_071315](https://github.com/user-attachments/assets/f40b4b3b-6de2-4373-828d-4aeb22906b9f)

Would the follow be acceptable instead?
![Screenshot_20241004_072606](https://github.com/user-attachments/assets/2fc3a5d1-3041-49ac-bb88-bb8b9e611a28)

2024-10-04 10:36 UTC, alanjds commented on src/pages/Background/index.js
> +                + '\nLast successful transmission was ' + lastSuccess),
I updated the message but the title got too big for one line:
![Screenshot_20241004_070643](https://github.com/user-attachments/assets/6806669c-6263-45c6-9feb-861e21abbb25)

Would be acceptable something like this instead?
![Screenshot_20241004_073439](https://github.com/user-attachments/assets/cc6aca66-0707-4217-ba4c-44b4b1895bd5)

2024-10-04 10:50 UTC, alanjds commented
@mjbradford89 Thanks for the updates.

Some of the titles became too big for one line. I changed these from "We had an issue submitting" to "Could not submit" and "There is an issue connecting" to "Could not connect".

Could you please take another look?

2024-10-04 15:55 UTC, mjbradford89 commented on src/pages/Background/index.js
> +                + '\nLast successful transmission was ' + lastSuccess),
Yep I think that is better actually :+1:

2024-10-04 16:13 UTC, mjbradford89 commented
hey @alanjds I think these changes look good.  But I am having an issue when testing.  When I install the extension and enter an API key, the request that validates it returns a 500 so the key is not validated correctly.  I think this is probably because the /v3/instance endpoint works differently than v2 :cry:.

![image](https://github.com/user-attachments/assets/bf9d866d-478d-4002-a949-0ba0861b09da)

2024-10-04 16:49 UTC, mjbradford89 commented
I created a pr that should fix the 500 error in AI: https://github.com/polyswarm/artifact-index/pull/1429/files

Hopefully this will fix the issue with the api key validation and no more changes are needed here.

2024-10-04 17:22 UTC, alanjds commented
> I created a pr that should fix the 500 error in AI. Hopefully this will fix the issue with the api key validation and no more changes are needed here.

I will revert the v2 -> v3 change. During my tests, v2 was working good

2024-10-04 17:24 UTC, alanjds commented
> hey @alanjds I think these changes look good. But I am having an issue when testing. When I install the extension and enter an API key, the request that validates it returns a 500 so the key is not validated correctly. I think this is probably because the /v3/instance endpoint works differently than v2 😢.
> 
> ![image](https://private-user-images.githubusercontent.com/6517855/373718427-bf9d866d-478d-4002-a949-0ba0861b09da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjI3NDAsIm5iZiI6MTcyODA2MjQ0MCwicGF0aCI6Ii82NTE3ODU1LzM3MzcxODQyNy1iZjlkODY2ZC00NzhkLTQwMDItYTk0OS0wYmEwODYxYjA5ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMTcyMDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ5OTdhODI4NWEzMmJkZDI1MzMyZDA5ZWVkNmViODI3NmFjNmVlNzE3N2Q3NzViYzAwMDE5ZmU3ZGFkMjcyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8mCgl3jvkwJVL5xO89DpfGPsxOEEtd9XtZ6XztYIywU)

@mjbradford89 I changed back to v2 in a828803. Please take another look.

2024-10-04 17:54 UTC, mjbradford89 approved these changes

2024-10-04 17:54 UTC, merged